FROM node:20-alpine

WORKDIR /app

# Installer pnpm
RUN npm install -g pnpm

# Copier uniquement les fichiers de dépendances
COPY package*.json pnpm-lock.yaml ./
COPY src/infrastructure/config/.env.dev .env
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

# Installer les dépendances dans l'image
RUN pnpm install

# Copier le reste du code (sans node_modules grâce à .dockerignore)
COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]
