// src/domain/errors/error-codes.ts

export const CodesError = {
  TITLE_REQUIRED: 'TITLE_REQUIRED',
  PUBLIC_ID_INVALID: 'PUBLIC_ID_INVALID',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  STATUS_INVALID: 'STATUS_INVALID',
  NAME_REQUIRED: 'NAME_REQUIRED',
  STAGE_INVALID: 'STAGE_INVALID',

  // Informations personnelles
  FIRST_NAME_REQUIRED: 'FIRST_NAME_REQUIRED',
  LAST_NAME_REQUIRED: 'LAST_NAME_REQUIRED',
  BIRTH_INVALID: 'BIRTH_INVALID',

  // Contact
  PHONE_INVALID: 'PHONE_INVALID',
  ADDRESS_REQUIRED: 'ADDRESS_REQUIRED',

  // Relations / références
  TALK_LANGUAGE_INVALID: 'TALK_LANGUAGE_INVALID',
  USER_INVALID: 'USER_INVALID',

  // Liens (optionnels mais validables)
  WHATSAPP_INVALID: 'WHATSAPP_INVALID',
  LINKEDIN_URL_INVALID: 'LINKEDIN_URL_INVALID',
  GITHUB_URL_INVALID: 'GITHUB_URL_INVALID',
  AVATAR_URL_INVALID: 'AVATAR_URL_INVALID',
} as const;

export type CodesError = typeof CodesError[keyof typeof CodesError];
